comment: false

coverage:
  round: up
  precision: 1

  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 2%
        only_pulls: true
