version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.3.1
    steps:
      - checkout
      - run: R -e "devtools::install(dep=T); rmarkdown::render('manuscripts/manuscript.Rmd')"

workflows:
  version: 2

  build_only:
    jobs:
      - build:
        filters:
          branches:
            only: master

